---
defaults:
  - /schema/scheduler: ddim
  - _self_
num_train_timesteps: 1000
beta_start: 0.0001
beta_end: 0.02
beta_schedule: 'linear'
trained_betas: null
timestep_values: null
clip_sample: true
set_alpha_to_one: true
tensor_format: 'pt'